# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/mercuryiot.functionapp/*
    exclude:
      - README.md
      - azure-pipelines.yaml
      - azure-pipelines-functions.yaml
      - mercuryiot.sln
      - src/mercuryiot.web/*
      - test/mercuryiot.test.web/*
pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Visual Studio Professional with MSDN (82ff2680-0183-486e-b8d7-693e550750cf)'
    appType: 'functionApp'
    appName: 'mercuryiotfunctions'
    deployToSlotOrASE: true
    resourceGroupName: 'sensor-monitoring'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'