# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net 5'
  inputs: 
    packageType: sdk
    version: 5.0.100-preview.3.20216.6
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: mercuryiot.sln

- task: DotNetCoreCLI@2
  displayName: 'dotnet build' 
  inputs:
    command: 'build'
    projects: mercuryiot.sln

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/mercuryiot.web/**/?(*.zip)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'