# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net 5'
  inputs: 
    packageType: sdk
    version: 5.0.100-preview.3.20216.6
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore solution file mercuryiot.sln'
  inputs:
    command: 'restore'
    projects: mercuryiot.sln

- task: DotNetCoreCLI@2
  displayName: 'Build solution file mercuryiot.sln' 
  inputs:
    command: 'build'
    projects: mercuryiot.sln