trigger:
  - none

variables:
  group: DeploymentVariables

stages:
- stage: StreamAnalyticsJob
  jobs:
  - job: BuildStreamAnaltics
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseDotNet@2
        displayName:  'Use .Net Preview'
        inputs:
          version: '5.0.x'
          includePreviewVersions: true
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 5.0.x
          performMultiLevelLookup: true
          includePreviewVersions: true
      - task: Npm@1
        displayName: 'Install stream analytics ci/cd package'
        inputs:
          command: 'custom'
          customCommand: 'sudo install -g azure-streamanalytics-cicd --unsafe-perm=true --allow-root'
      - task: DotNetCoreCLI@2
        displayName: 'Restored Nuget packages.'
        inputs:
          command: restore 
          projects: '**/*Mercury.StreamAnalytics.asaproj'
      - task: DotNetCoreCLI@2
        displayName: 'Build stream analytics prokect'
        inputs:
          command: build
          projects: '**/*Mercury.StreamAnalytics.asaproj'
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          sourceFolder: $(system.defaultworkingdirectory)/$(outputPath)/
          contents: '**' 
          targetFolder: $(build.artifactstagingdirectory)
      - task: PublishBuildArtifacts@1
        displayName: 'Public artifact: drop'
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'drop'
- stage: ResourceDeployment
  dependsOn: StreamAnalyticsJob
  jobs:
    - job: DeployResourceGroup
      pool:
        vmImage: 'ubuntu-latest'
      displayName: 'Create Resource Group and Resources'
      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Create or update resource group'
        inputs:
          azureResourceManagerConnection: 'VSProSubscription'
          subscriptionId: '$(deploymentSubscription)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'mercury-iot'
          location: 'Central US'
          templateLocation: 'URL of the file'
          csmFileLink: 'https://raw.githubusercontent.com/mhenderson442/mercury-iot/master/templates/mercury-iot-template.json'
          csmParametersFileLink: 'https://raw.githubusercontent.com/mhenderson442/mercury-iot/master/templates/mercury-iot-template.parameters.json'
          deploymentMode: 'Incremental'   