trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: DeploymentVariables

jobs:
  - job: CreateResourceGroup
    displayName: 'Delete resource group and resources.'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Delete resource group.'
      inputs:
        azureResourceManagerConnection: 'VSProSubscription'
        subscriptionId: '$(deploymentSubscription)'
        action: 'DeleteRG'
        resourceGroupName: 'mercury-iot'
        location: 'North Central US' 
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/mhenderson442/mercury-iot/master/templates/mercury-iot-template.json'
        csmParametersFileLink: 'https://raw.githubusercontent.com/mhenderson442/mercury-iot/master/templates/mercury-iot-template.parameters.json'
        deploymentMode: 'Incremental'   