trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: DeploymentVariables

jobs:
  - job: CreateResourceGroup
    displayName: 'Delete Resource Group'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Delete Resource Group and Resources'
      inputs:
        azureResourceManagerConnection: 'VSProSubscription'
        subscriptionId: '$(deploymentSubscription)'
        action: 'DeleteRG'
        resourceGroupName: 'mercury-iot'
        location: 'North Central US'       
