trigger:
  - none

pool:
  vmImage: 'Hosted Windows 2019 with VS2019'

variables:
  group: DeploymentVariables

jobs:
  - job: hello
    steps:
    - script: echo hello yaml.
    - task: AzureResourceGroupDeployment@2
      displayName: 'Create or update resource group'
      inputs:
        azureSubscription: 'VSProSubscription'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'mercury-iot'
        location: 'North Central US'
        
        

        
