trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: DeploymentVariables

jobs:
  - job: CreateResourceGroup
    displayName: 'Delete resource group and resources.'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Delete resource group.'
      inputs:
        azureResourceManagerConnection: 'VSProSubscription'
        subscriptionId: $(deploymentSubscription)
        action: 'DeleteRG'
        resourceGroupName: 'mercury-iot'
        location: 'North Central US'    