trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: DeploymentVariables

jobs:
  - job: hello
    steps:
    - script: echo hello yaml.
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Create or update resource group'
      inputs:
        azureResourceManagerConnection: 'VSProSubscription'
        subscriptionId: '$(deploymentSubscription)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'mercury-iot'
        location: 'North Central US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://github.com/mhenderson442/mercury-iot/blob/master/templates/mercury-iot-template.json'
        csmParametersFileLink: 'https://github.com/mhenderson442/mercury-iot/blob/master/templates/mercury-iot-template.parameters.json'

        
