trigger:
  - none

variables:
  - group: deploymentVariables
  - group: deploymentSecrets

stages:
  - stage: tme
    jobs:
      - job: deployMercuryIot
        displayName: "Create Or Update Resource Group"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Azure Resource Manager Template Deployment"
            inputs:
              deploymentScope: "Resource Group"
              location: $(location)
              azureResourceManagerConnection: $(azureResourceManagerConnection)
              templateLocation: "URL of the file"
              csmFileLink: $(csmFileLink)
              csmParametersFileLink: $(csmParametersFileLink)
              deploymentMode: "Incremental"
              subscriptionId: $(deploymentSubscriptionId)
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroupName)
