trigger:
  - none

variables:
  - group: deploymentVariables
  - group: deploymentSecrets

stages:
  - stage: tme
    jobs:
      - job: buildStreamAnaltics
        displayName: "Create Or Update Resource Group"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Azure Resource Manager Template Deployment"
            inputs:
              deploymentScope: "Resource Group"
              location: $(location)
              azureResourceManagerConnection: $(azureResourceManagerConnection)
              templateLocation: "URL of the file"
              csmFileLink: "https://raw.githubusercontent.com/mhenderson442/mercury-iot/master/templates/mercury-iot-template.json"
              csmParametersFileLink: "https://raw.githubusercontent.com/mhenderson442/mercury-iot/master/templates/mercury-iot-template.parameters.json"
              deploymentMode: "Incremental"
              subscriptionId: $(deploymentSubscriptionId)
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroupName)
